version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - goconst
    - misspell
    - revive
    - unconvert
    - unparam
    - nakedret
    - bodyclose
    - errorlint
    - copyloopvar
    - noctx
    - gosec
    - gocritic

  settings:
    revive:
      enable-default-rules: true
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true
    gosec:
      excludes:
        - G704
        - G117
        - G101

issues:
  new: true
